import { ToolItem, ActivityItem, IncludedServiceItem, ExcludedServiceItem } from "@/types/proposal";

export const INITIAL_TOOLS: ToolItem[] = [
  {
    name: "TacticalRMM",
    category: "Soporte remoto",
    description:
      "Monitoreo de equipos, inventario, alertas, automatización, ejecución remota de tareas y acceso remoto autorizado.",
    supportLevel: "Avanzado",
    included: true,
    includedInHours: true,
    requiresApproval: false,
    separateQuote: false,
    licenseIncluded: true,
    notes: "Agente desplegado en estaciones de trabajo autorizadas.",
    displayOrder: 1,
  },
  {
    name: "Saint",
    category: "Administración empresarial",
    description:
      "Soporte para módulos administrativos, contables, inventario, facturación, compras, ventas y reportes. La cobertura exacta se configura según los módulos activos del cliente.",
    supportLevel: "Especializado",
    included: true,
    includedInHours: true,
    requiresApproval: false,
    separateQuote: false,
    licenseIncluded: false,
    notes: "No incluye licencias Saint ni módulos de terceros no convenidos.",
    displayOrder: 2,
  },
  {
    name: "VPN ZetaNet",
    category: "Conectividad segura",
    description:
      "Configuración de perfiles, acceso remoto seguro, diagnóstico de conexión y asistencia para usuarios autorizados.",
    supportLevel: "Estándar",
    included: true,
    includedInHours: true,
    requiresApproval: false,
    separateQuote: false,
    licenseIncluded: false,
    notes: "Soporte sobre enlaces existentes provistos por el cliente.",
    displayOrder: 3,
  },
  {
    name: "ContaExperto",
    category: "Contabilidad",
    description:
      "Instalación, configuración, mantenimiento y soporte funcional básico del software contable.",
    supportLevel: "Estándar",
    included: true,
    includedInHours: true,
    requiresApproval: false,
    separateQuote: false,
    licenseIncluded: false,
    notes: "Aplica sobre base de datos reportada en la auditoría inicial.",
    displayOrder: 4,
  },
  {
    name: "Microsoft 365",
    category: "Productividad",
    description:
      "Configuración y soporte para Outlook, Word, Excel, Teams, OneDrive y cuentas de usuario corporativas.",
    supportLevel: "Estándar",
    included: true,
    includedInHours: true,
    requiresApproval: false,
    separateQuote: false,
    licenseIncluded: false,
    notes: "Licenciamiento provisto por el cliente o cotizado aparte.",
    displayOrder: 5,
  },
  {
    name: "Respaldo administrado",
    category: "Continuidad operativa",
    description:
      "Revisión de tareas de respaldo, validación básica, restauración de prueba periódica y seguimiento de errores.",
    supportLevel: "Preventivo",
    included: true,
    includedInHours: true,
    requiresApproval: false,
    separateQuote: false,
    licenseIncluded: false,
    notes: "Almacenamiento físico o cloud provisto por el cliente.",
    displayOrder: 6,
  },
  {
    name: "Protección de equipos",
    category: "Seguridad",
    description:
      "Configuración de antivirus corporativo, parches de seguridad, revisión de alertas y medidas preventivas.",
    supportLevel: "Preventivo / Correctivo",
    included: true,
    includedInHours: true,
    requiresApproval: false,
    separateQuote: false,
    licenseIncluded: false,
    notes: "Gestión centralizada del estado de seguridad de los terminales.",
    displayOrder: 7,
  },
  {
    name: "Impresoras y periféricos",
    category: "Operación",
    description:
      "Instalación, configuración y diagnóstico remoto de impresoras, escáneres y dispositivos de red compatibles.",
    supportLevel: "Estándar",
    included: true,
    includedInHours: true,
    requiresApproval: false,
    separateQuote: false,
    licenseIncluded: false,
    notes: "Reparación física de hardware y consumibles requieren cotización.",
    displayOrder: 8,
  },
  {
    name: "Redes e infraestructura",
    category: "Conectividad",
    description:
      "Diagnóstico lógico de red, configuración básica de routers/switches y evaluación de conectividad empresarial.",
    supportLevel: "Estándar",
    included: true,
    includedInHours: true,
    requiresApproval: false,
    separateQuote: false,
    licenseIncluded: false,
    notes: "Los trabajos físicos (cableado, perforaciones) deben cotizarse por separado.",
    displayOrder: 9,
  },
  {
    name: "CCTV",
    category: "Videovigilancia",
    description:
      "Soporte básico para visualización, acceso remoto y configuración lógica de grabadores NVR/DVR.",
    supportLevel: "Básico lógico",
    included: true,
    includedInHours: true,
    requiresApproval: false,
    separateQuote: false,
    licenseIncluded: false,
    notes: "Instalación física, cableado, reemplazo de cámaras y reparación deben cotizarse por separado.",
    displayOrder: 10,
  },
];

export const INITIAL_ACTIVITIES: ActivityItem[] = [
  {
    name: "Soporte rápido remoto",
    category: "Atención inmediata",
    description: "Revisión rápida de errores menores, desbloqueo de cuentas, reseteo de claves y dudas funcionales.",
    minMinutes: 15,
    maxMinutes: 30,
    consumesHours: true,
    included: true,
    requiresApproval: false,
    separateQuote: false,
    displayOrder: 1,
  },
  {
    name: "Soporte técnico estándar",
    category: "Mantenimiento correctivo",
    description: "Diagnóstico activo, instalación y configuración de programas, impresoras y optimización de terminales.",
    minMinutes: 30,
    maxMinutes: 90,
    consumesHours: true,
    included: true,
    requiresApproval: false,
    separateQuote: false,
    displayOrder: 2,
  },
  {
    name: "Soporte avanzado y especializado",
    category: "Intervención de alto nivel",
    description: "Resolución de incidencias en Saint, servidores, respaldos críticos, reestructuración lógica de perfiles.",
    minMinutes: 90,
    maxMinutes: 240,
    consumesHours: true,
    included: true,
    requiresApproval: false,
    separateQuote: false,
    displayOrder: 3,
  },
  {
    name: "Monitoreo automatizado 24/7",
    category: "Proactivo",
    description: "Vigilancia de telemetría, alertas automáticas de disco, memoria y estado de servicios en TacticalRMM.",
    minMinutes: 0,
    maxMinutes: 0,
    consumesHours: false, // NO consume horas
    included: true,
    requiresApproval: false,
    separateQuote: false,
    displayOrder: 4,
  },
  {
    name: "Descargas y actualizaciones desatendidas",
    category: "Automatización",
    description: "Aplicación nocturna de parches de seguridad y reinicios programados sin requerir conexión activa.",
    minMinutes: 0,
    maxMinutes: 0,
    consumesHours: false, // NO consume horas
    included: true,
    requiresApproval: false,
    separateQuote: false,
    displayOrder: 5,
  },
  {
    name: "Instalación inicial de agentes RMM",
    category: "Despliegue",
    description: "Despliegue del agente de telemetría y seguridad en los equipos acordados del cliente.",
    minMinutes: 0,
    maxMinutes: 0,
    consumesHours: false, // NO consume horas en la propuesta inicial
    included: true,
    requiresApproval: false,
    separateQuote: false,
    displayOrder: 6,
  },
  {
    name: "Software nuevo no reportado inicialmente",
    category: "Gestión de cambio",
    description: "Integración o diagnóstico sobre plataformas informáticas no declaradas al inicio de la contratación.",
    minMinutes: 60,
    maxMinutes: 180,
    consumesHours: true,
    included: false, // Requiere evaluación y aprobación
    requiresApproval: true,
    separateQuote: false,
    displayOrder: 7,
  },
];

export const INITIAL_INCLUDED_SERVICES: IncludedServiceItem[] = [
  {
    id: "inc-1",
    title: "Mesa de Ayuda y Soporte Remoto",
    description: "Atención preferencial por canales oficiales de Net & Soft en horario comercial.",
    category: "Soporte",
  },
  {
    id: "inc-2",
    title: "Mantenimiento Lógico Preventivo",
    description: "Limpieza de temporales, control de parches y optimización periódica de rendimiento.",
    category: "Mantenimiento",
  },
  {
    id: "inc-3",
    title: "Auditoría Continua de Respaldos",
    description: "Verificación de la integridad de copias de seguridad de Saint y documentos clave.",
    category: "Continuidad",
  },
  {
    id: "inc-4",
    title: "Gestión Proactiva de Seguridad",
    description: "Seguimiento centralizado contra virus, software espía y vulnerabilidades comunes.",
    category: "Seguridad",
  },
  {
    id: "inc-5",
    title: "Reportes Periódicos de Consumo de Horas",
    description: "Transparencia absoluta con detalle de cada intervención, tiempo utilizado y tiempo restante.",
    category: "Gestión",
  },
];

export const INITIAL_EXCLUDED_SERVICES: ExcludedServiceItem[] = [
  {
    id: "exc-1",
    title: "Trabajos físicos de cableado o infraestructura",
    description: "Tendido de cable de red, canaletas, ductos, fibra óptica y perforaciones en sitio.",
    separateQuoteNotice: "Requiere cotización por proyecto separado.",
  },
  {
    id: "exc-2",
    title: "Reparación física y sustitución de hardware",
    description: "Costes de repuestos, fuentes de poder, discos duros, memorias o cambio de pantallas.",
    separateQuoteNotice: "Los repuestos son adquiridos por el cliente o cotizados de forma independiente.",
  },
  {
    id: "exc-3",
    title: "Costes de licencias de terceros",
    description: "Licencias de Saint, Microsoft 365, ContaExperto o enlaces de conectividad de operadoras.",
    separateQuoteNotice: "Debe ser provisto directamente por el cliente.",
  },
  {
    id: "exc-4",
    title: "Instalación física de cámaras y cableado CCTV",
    description: "Montaje en alturas, tuberías conduit y fijación de soportes para cámaras de seguridad.",
    separateQuoteNotice: "Requiere levantamiento técnico y cotización por separado.",
  },
];

export const INITIAL_TERMS: string[] = [
  "El precio mensual cubre la cantidad estipulada de horas incluidas para el período de 30 días calendario.",
  "Las intervenciones técnicas consumen horas en bloques de tiempo según la duración de la sesión registrada en el ticket de atención.",
  "El monitoreo preventivo automatizado 24/7 y la recepción de alertas proactivas no consumen horas del plan.",
  "Al alcanzar el porcentaje de alerta configurado, se notificará al contacto designado para autorizar horas adicionales o planificar tareas.",
  "Las horas adicionales ejecutadas bajo previa autorización se facturan al precio por hora acordado al cierre del período.",
  "Los servicios no utilizados durante el mes no son acumulables salvo que se especifique la condición de rollover en la propuesta.",
  "La propuesta comercial tiene un período de validez de 15 días a partir de la fecha de emisión.",
  "El presente documento confirma la intención de contratación de servicios y no realiza cobros automáticos.",
];
